/**
 * Test data interface representing the information of a member.
 *
 * @property {number} id - Numeric identifier.
 * @property {string} name - String value for alphabetical sorting.
 * @property {number} age - Numeric value for sorting by numbers.
 * @property {boolean} active - Boolean value for sorting by true/false.
 * @property {string} joinDate - Date value in ISO 8601 format for sorting chronologically.
 * @property {number} score - Floating-point number for advanced sorting.
 * @property {string} department - String category for group sorting.
 */
export interface MemberInformation {
  id: number;
  name: string;
  age: number;
  active: boolean;
  joinDate: string;
  score: number;
  department: string;
}

/**
 * A constant test data array of member information objects.
 * Each object represents a member with various attributes such as id, name, age, active status, join date, score, and department.
 *
 * @constant
 * @type {MemberInformation[]}
 *
 * @property {number} id - The unique identifier for the member.
 * @property {string} name - The name of the member.
 * @property {number} age - The age of the member.
 * @property {boolean} active - The active status of the member.
 * @property {string} joinDate - The date the member joined, in YYYY-MM-DD format.
 * @property {number} score - The performance score of the member.
 * @property {string} department - The department the member belongs to.
 */
export const MEMBER_DATA: MemberInformation[] = [
  {
    id: 1,
    name: "Alice",
    age: 25,
    active: true,
    joinDate: "2022-01-15",
    score: 95.5,
    department: "Engineering",
  },
  {
    id: 2,
    name: "Bob",
    age: 30,
    active: false,
    joinDate: "2021-12-10",
    score: 88.0,
    department: "HR",
  },
  {
    id: 3,
    name: "Charlie",
    age: 22,
    active: true,
    joinDate: "2023-03-05",
    score: 72.4,
    department: "Marketing",
  },
  {
    id: 4,
    name: "Diana",
    age: 28,
    active: false,
    joinDate: "2020-08-19",
    score: 81.3,
    department: "Engineering",
  },
  {
    id: 5,
    name: "Eve",
    age: 35,
    active: true,
    joinDate: "2019-07-22",
    score: 91.2,
    department: "Finance",
  },
  {
    id: 6,
    name: "Frank",
    age: 29,
    active: false,
    joinDate: "2021-11-11",
    score: 67.8,
    department: "HR",
  },
  {
    id: 7,
    name: "Grace",
    age: 24,
    active: true,
    joinDate: "2022-05-14",
    score: 85.0,
    department: "Marketing",
  },
  {
    id: 8,
    name: "Hank",
    age: 40,
    active: true,
    joinDate: "2018-03-03",
    score: 78.9,
    department: "Finance",
  },
  {
    id: 9,
    name: "Ivy",
    age: 32,
    active: false,
    joinDate: "2023-02-01",
    score: 92.7,
    department: "Engineering",
  },
  {
    id: 10,
    name: "Jack",
    age: 27,
    active: true,
    joinDate: "2020-06-16",
    score: 74.5,
    department: "HR",
  },
  {
    id: 11,
    name: "Kelly",
    age: 34,
    active: false,
    joinDate: "2019-05-10",
    score: 87.6,
    department: "Marketing",
  },
  {
    id: 12,
    name: "Leo",
    age: 31,
    active: true,
    joinDate: "2022-07-25",
    score: 90.4,
    department: "Finance",
  },
  {
    id: 13,
    name: "Mona",
    age: 26,
    active: true,
    joinDate: "2021-09-08",
    score: 76.2,
    department: "Engineering",
  },
  {
    id: 14,
    name: "Nate",
    age: 23,
    active: false,
    joinDate: "2023-04-22",
    score: 80.3,
    department: "HR",
  },
  {
    id: 15,
    name: "Olivia",
    age: 36,
    active: true,
    joinDate: "2019-12-18",
    score: 89.1,
    department: "Marketing",
  },
  {
    id: 16,
    name: "Paul",
    age: 28,
    active: false,
    joinDate: "2020-10-30",
    score: 82.5,
    department: "Finance",
  },
  {
    id: 17,
    name: "Quinn",
    age: 27,
    active: true,
    joinDate: "2022-03-12",
    score: 69.7,
    department: "Engineering",
  },
  {
    id: 18,
    name: "Rose",
    age: 33,
    active: false,
    joinDate: "2021-06-20",
    score: 75.6,
    department: "HR",
  },
  {
    id: 19,
    name: "Steve",
    age: 29,
    active: true,
    joinDate: "2020-09-01",
    score: 93.4,
    department: "Marketing",
  },
  {
    id: 20,
    name: "Tina",
    age: 21,
    active: true,
    joinDate: "2023-05-17",
    score: 64.3,
    department: "Finance",
  },
  {
    id: 21,
    name: "Uma",
    age: 30,
    active: false,
    joinDate: "2019-08-12",
    score: 86.1,
    department: "Engineering",
  },
  {
    id: 22,
    name: "Victor",
    age: 38,
    active: true,
    joinDate: "2020-11-07",
    score: 77.5,
    department: "HR",
  },
  {
    id: 23,
    name: "Wendy",
    age: 29,
    active: true,
    joinDate: "2022-02-14",
    score: 89.9,
    department: "Marketing",
  },
  {
    id: 24,
    name: "Xander",
    age: 41,
    active: false,
    joinDate: "2018-06-01",
    score: 72.8,
    department: "Finance",
  },
  {
    id: 25,
    name: "Yara",
    age: 26,
    active: true,
    joinDate: "2023-07-09",
    score: 91.3,
    department: "Engineering",
  },
  {
    id: 26,
    name: "Zane",
    age: 22,
    active: false,
    joinDate: "2021-04-11",
    score: 68.4,
    department: "HR",
  },
  {
    id: 27,
    name: "Abby",
    age: 35,
    active: true,
    joinDate: "2019-02-17",
    score: 83.9,
    department: "Marketing",
  },
  {
    id: 28,
    name: "Brian",
    age: 37,
    active: false,
    joinDate: "2020-01-24",
    score: 74.0,
    department: "Finance",
  },
  {
    id: 29,
    name: "Clara",
    age: 28,
    active: true,
    joinDate: "2021-10-15",
    score: 80.1,
    department: "Engineering",
  },
  {
    id: 30,
    name: "Derek",
    age: 31,
    active: false,
    joinDate: "2022-08-06",
    score: 92.2,
    department: "HR",
  },
  {
    id: 31,
    name: "Ella",
    age: 39,
    active: true,
    joinDate: "2023-01-10",
    score: 79.3,
    department: "Marketing",
  },
  {
    id: 32,
    name: "Finn",
    age: 40,
    active: true,
    joinDate: "2020-05-14",
    score: 88.5,
    department: "Finance",
  },
  {
    id: 33,
    name: "Gina",
    age: 29,
    active: false,
    joinDate: "2019-09-22",
    score: 67.9,
    department: "Engineering",
  },
  {
    id: 34,
    name: "Harry",
    age: 25,
    active: true,
    joinDate: "2022-03-01",
    score: 94.7,
    department: "HR",
  },
  {
    id: 35,
    name: "Isla",
    age: 33,
    active: true,
    joinDate: "2021-12-25",
    score: 84.3,
    department: "Marketing",
  },
  {
    id: 36,
    name: "Jake",
    age: 27,
    active: false,
    joinDate: "2023-04-14",
    score: 70.6,
    department: "Finance",
  },
  {
    id: 37,
    name: "Kara",
    age: 34,
    active: true,
    joinDate: "2018-08-18",
    score: 89.7,
    department: "Engineering",
  },
  {
    id: 38,
    name: "Liam",
    age: 23,
    active: true,
    joinDate: "2023-09-07",
    score: 76.8,
    department: "HR",
  },
  {
    id: 39,
    name: "Mila",
    age: 36,
    active: true,
    joinDate: "2021-11-11",
    score: 88.1,
    department: "Marketing",
  },
  {
    id: 40,
    name: "Noah",
    age: 28,
    active: true,
    joinDate: "2019-10-20",
    score: 93.0,
    department: "Finance",
  },
  {
    id: 41,
    name: "Oscar",
    age: 39,
    active: false,
    joinDate: "2020-07-07",
    score: 81.5,
    department: "Engineering",
  },
  {
    id: 42,
    name: "Piper",
    age: 26,
    active: true,
    joinDate: "2022-04-12",
    score: 65.4,
    department: "HR",
  },
  {
    id: 43,
    name: "Quincy",
    age: 24,
    active: true,
    joinDate: "2023-08-03",
    score: 90.0,
    department: "Marketing",
  },
  {
    id: 44,
    name: "Ruby",
    age: 37,
    active: false,
    joinDate: "2021-03-09",
    score: 74.7,
    department: "Finance",
  },
  {
    id: 45,
    name: "Sam",
    age: 29,
    active: true,
    joinDate: "2020-02-02",
    score: 95.1,
    department: "Engineering",
  },
  {
    id: 46,
    name: "Tess",
    age: 30,
    active: true,
    joinDate: "2022-06-05",
    score: 86.2,
    department: "HR",
  },
  {
    id: 47,
    name: "Ursula",
    age: 25,
    active: false,
    joinDate: "2019-04-15",
    score: 68.5,
    department: "Marketing",
  },
  {
    id: 48,
    name: "Violet",
    age: 28,
    active: true,
    joinDate: "2023-02-26",
    score: 82.3,
    department: "Finance",
  },
  {
    id: 49,
    name: "Will",
    age: 32,
    active: true,
    joinDate: "2021-08-20",
    score: 77.6,
    department: "Engineering",
  },
  {
    id: 50,
    name: "Xena",
    age: 31,
    active: true,
    joinDate: "2020-12-28",
    score: 92.9,
    department: "HR",
  },
];
