/**
 * Test data interface representing the information of a member.
 *
 * @property {number} id - Numeric identifier.
 * @property {string} name - String value for alphabetical sorting.
 * @property {number} age - Numeric value for sorting by numbers.
 * @property {boolean} active - Boolean value for sorting by true/false.
 * @property {string} joinDate - Date value in ISO 8601 format for sorting chronologically.
 * @property {number} score - Floating-point number for advanced sorting.
 * @property {string} department - String category for group sorting.
 * @property {string} comment - String value for additional information.
 */
export interface MemberInformation {
  id: number;
  name: string;
  age: number;
  active: boolean;
  joinDate: string;
  score: number;
  department: string;
  comment: string | null | undefined;
}

/**
 * A constant test data array of member information objects.
 * Each object represents a member with various attributes such as id, name, age, active status, join date, score, and department.
 *
 * @constant
 * @type {MemberInformation[]}
 *
 * @property {number} id - The unique identifier for the member.
 * @property {string} name - The name of the member.
 * @property {number} age - The age of the member.
 * @property {boolean} active - The active status of the member.
 * @property {string} joinDate - The date the member joined, in YYYY-MM-DD format.
 * @property {number} score - The performance score of the member.
 * @property {string} department - The department the member belongs to.
 */
export const MEMBER_DATA: MemberInformation[] = [
  {
    id: 1,
    name: "Alice",
    age: 45,
    active: true,
    joinDate: "2023-10-27",
    score: 82.3,
    department: "Engineering",
    comment: null,
  },
  {
    id: 2,
    name: "Bob",
    age: 24,
    active: false,
    joinDate: "2020-12-08",
    score: 76.6,
    department: "Engineering",
    comment: "Veteran employee",
  },
  {
    id: 3,
    name: "Charlie",
    age: 33,
    active: false,
    joinDate: "2021-06-05",
    score: 63.8,
    department: "Engineering",
    comment: "Promoted recently",
  },
  {
    id: 4,
    name: "Diana",
    age: 49,
    active: false,
    joinDate: "2021-09-08",
    score: 81.2,
    department: "HR",
    comment: "Promoted recently",
  },
  {
    id: 5,
    name: "Eve",
    age: 53,
    active: true,
    joinDate: "2020-03-27",
    score: 73.6,
    department: "Finance",
    comment: "High potential",
  },
  {
    id: 6,
    name: "Frank",
    age: 39,
    active: false,
    joinDate: "2022-08-11",
    score: 84.8,
    department: "Finance",
    comment: "Needs improvement",
  },
  {
    id: 7,
    name: "Grace",
    age: 21,
    active: true,
    joinDate: "2023-11-16",
    score: 96.8,
    department: "HR",
    comment: "Mentor to new hires",
  },
  {
    id: 8,
    name: "Hank",
    age: 47,
    active: false,
    joinDate: "2021-02-20",
    score: 81.1,
    department: "HR",
    comment: "Promoted recently",
  },
  {
    id: 9,
    name: "Ivy",
    age: 20,
    active: false,
    joinDate: "2020-02-21",
    score: 68.9,
    department: "Engineering",
    comment: "High potential",
  },
  {
    id: 10,
    name: "Jack",
    age: 53,
    active: true,
    joinDate: "2022-02-15",
    score: 76.1,
    department: "Marketing",
    comment: "High potential",
  },
  {
    id: 11,
    name: "Kelly",
    age: 55,
    active: true,
    joinDate: "2022-03-24",
    score: 99.2,
    department: "Marketing",
    comment: null,
  },
  {
    id: 12,
    name: "Leo",
    age: 26,
    active: true,
    joinDate: "2022-04-02",
    score: 61.8,
    department: "Marketing",
    comment: null,
  },
  {
    id: 13,
    name: "Mona",
    age: 41,
    active: true,
    joinDate: "2021-05-16",
    score: 69.2,
    department: "Finance",
    comment: "High potential",
  },
  {
    id: 14,
    name: "Nate",
    age: 59,
    active: false,
    joinDate: "2023-08-12",
    score: 73.2,
    department: "Marketing",
    comment: null,
  },
  {
    id: 15,
    name: "Olivia",
    age: 42,
    active: false,
    joinDate: "2021-11-03",
    score: 87.7,
    department: "Engineering",
    comment: null,
  },
  {
    id: 16,
    name: "Paul",
    age: 39,
    active: false,
    joinDate: "2023-07-09",
    score: 75.9,
    department: "Engineering",
    comment: "Mentor to new hires",
  },
  {
    id: 17,
    name: "Quinn",
    age: 58,
    active: false,
    joinDate: "2021-01-12",
    score: 69.8,
    department: "Engineering",
    comment: "Needs improvement",
  },
  {
    id: 18,
    name: "Rose",
    age: 22,
    active: true,
    joinDate: "2020-01-21",
    score: 82.2,
    department: "Marketing",
    comment: "Promoted recently",
  },
  {
    id: 19,
    name: "Steve",
    age: 40,
    active: true,
    joinDate: "2023-06-28",
    score: 79.6,
    department: "Engineering",
    comment: "High potential",
  },
  {
    id: 20,
    name: "Tina",
    age: 37,
    active: true,
    joinDate: "2022-12-09",
    score: 84.4,
    department: "HR",
    comment: null,
  },
  {
    id: 21,
    name: "Uma",
    age: 23,
    active: false,
    joinDate: "2022-11-16",
    score: 99.9,
    department: "HR",
    comment: "Needs improvement",
  },
  {
    id: 22,
    name: "Victor",
    age: 33,
    active: false,
    joinDate: "2020-09-25",
    score: 95.6,
    department: "Engineering",
    comment: null,
  },
  {
    id: 23,
    name: "Wendy",
    age: 32,
    active: true,
    joinDate: "2021-03-23",
    score: 84.1,
    department: "Finance",
    comment: null,
  },
  {
    id: 24,
    name: "Xander",
    age: 45,
    active: false,
    joinDate: "2022-06-20",
    score: 98.6,
    department: "Finance",
    comment: "Needs improvement",
  },
  {
    id: 25,
    name: "Yara",
    age: 39,
    active: true,
    joinDate: "2022-10-04",
    score: 99.9,
    department: "HR",
    comment: "Mentor to new hires",
  },
  {
    id: 26,
    name: "Zane",
    age: 21,
    active: false,
    joinDate: "2020-01-27",
    score: 62.8,
    department: "Engineering",
    comment: null,
  },
  {
    id: 27,
    name: "Aaron",
    age: 52,
    active: false,
    joinDate: "2022-12-05",
    score: 90.3,
    department: "Marketing",
    comment: "Promoted recently",
  },
  {
    id: 28,
    name: "Bella",
    age: 35,
    active: false,
    joinDate: "2022-09-09",
    score: 98.0,
    department: "Engineering",
    comment: "Promoted recently",
  },
  {
    id: 29,
    name: "Cindy",
    age: 32,
    active: true,
    joinDate: "2023-04-16",
    score: 92.0,
    department: "Engineering",
    comment: "Mentor to new hires",
  },
  {
    id: 30,
    name: "David",
    age: 39,
    active: true,
    joinDate: "2022-01-12",
    score: 84.9,
    department: "Marketing",
    comment: "High potential",
  },
  {
    id: 31,
    name: "Ethan",
    age: 48,
    active: true,
    joinDate: "2022-01-11",
    score: 85.7,
    department: "Engineering",
    comment: "Promoted recently",
  },
  {
    id: 32,
    name: "Fiona",
    age: 42,
    active: false,
    joinDate: "2022-05-25",
    score: 94.9,
    department: "HR",
    comment: "Needs improvement",
  },
  {
    id: 33,
    name: "Gina",
    age: 35,
    active: true,
    joinDate: "2020-11-16",
    score: 72.5,
    department: "Marketing",
    comment: "High potential",
  },
  {
    id: 34,
    name: "Harry",
    age: 21,
    active: false,
    joinDate: "2021-12-19",
    score: 83.5,
    department: "Engineering",
    comment: "Mentor to new hires",
  },
  {
    id: 35,
    name: "Isla",
    age: 58,
    active: true,
    joinDate: "2021-08-28",
    score: 63.6,
    department: "HR",
    comment: "Veteran employee",
  },
  {
    id: 36,
    name: "Jake",
    age: 59,
    active: true,
    joinDate: "2023-09-02",
    score: 98.7,
    department: "Engineering",
    comment: "Needs improvement",
  },
  {
    id: 37,
    name: "Kara",
    age: 26,
    active: true,
    joinDate: "2023-10-25",
    score: 79.0,
    department: "HR",
    comment: "Mentor to new hires",
  },
  {
    id: 38,
    name: "Liam",
    age: 56,
    active: true,
    joinDate: "2022-03-14",
    score: 88.1,
    department: "Engineering",
    comment: "Needs improvement",
  },
  {
    id: 39,
    name: "Mila",
    age: 23,
    active: false,
    joinDate: "2020-07-07",
    score: 88.1,
    department: "Marketing",
    comment: null,
  },
  {
    id: 40,
    name: "Nora",
    age: 40,
    active: false,
    joinDate: "2022-10-06",
    score: 65.3,
    department: "HR",
    comment: null,
  },
  {
    id: 41,
    name: "Owen",
    age: 34,
    active: false,
    joinDate: "2020-03-28",
    score: 73.3,
    department: "HR",
    comment: "Promoted recently",
  },
  {
    id: 42,
    name: "Paula",
    age: 30,
    active: false,
    joinDate: "2023-07-23",
    score: 88.9,
    department: "Engineering",
    comment: "Promoted recently",
  },
  {
    id: 43,
    name: "Quincy",
    age: 52,
    active: true,
    joinDate: "2021-07-09",
    score: 73.4,
    department: "HR",
    comment: "High potential",
  },
  {
    id: 44,
    name: "Rachel",
    age: 30,
    active: false,
    joinDate: "2020-11-26",
    score: 80.0,
    department: "Finance",
    comment: "Needs improvement",
  },
  {
    id: 45,
    name: "Sam",
    age: 52,
    active: true,
    joinDate: "2023-01-24",
    score: 88.5,
    department: "Marketing",
    comment: "High potential",
  },
  {
    id: 46,
    name: "Tessa",
    age: 45,
    active: false,
    joinDate: "2021-02-25",
    score: 74.8,
    department: "Finance",
    comment: "High potential",
  },
  {
    id: 47,
    name: "Ursula",
    age: 40,
    active: true,
    joinDate: "2020-05-16",
    score: 97.8,
    department: "Finance",
    comment: "Veteran employee",
  },
  {
    id: 48,
    name: "Vincent",
    age: 31,
    active: false,
    joinDate: "2023-12-20",
    score: 65.8,
    department: "HR",
    comment: "High potential",
  },
  {
    id: 49,
    name: "Will",
    age: 38,
    active: false,
    joinDate: "2020-12-05",
    score: 67.5,
    department: "Engineering",
    comment: "Promoted recently",
  },
  {
    id: 50,
    name: "Xena",
    age: 39,
    active: true,
    joinDate: "2023-11-26",
    score: 95.2,
    department: "HR",
    comment: "Veteran employee",
  },
];
