on:
  workflow_call:
    inputs:
      pnpm_store_path:
        required: true
        type: string

jobs:
  build_library:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ inputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Restore dependencies
        run: pnpm install --frozen-lockfile
      - name: Build for production
        run: pnpm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: library
          path: dist/lib
          retention-days: 5

  build_demo:
    name: Build Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ inputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Restore dependencies
        run: pnpm install --frozen-lockfile
      - name: Update application version
        run: sed -i "s/APP_VERSION = \".*\"/APP_VERSION = \"v$(jq -r .version package.json)-$(git rev-parse --short HEAD)\"/g" projects/demo/src/app/app.component.ts
      - name: Build for production
        run: pnpm run build:demo
      - name: Upload artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/demo/browser
