name: Continuous Integration
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - v18
      - v17

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/shared.yml
    secrets: inherit
