name: Continuous Deployment

on:
  push:
    branches:
      - main
      - v17
      - v18

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/shared.yml
    secrets: inherit

  deploy_demo:
    name: Deploy Demo
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ci]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy_library:
    name: Deploy Library
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    runs-on: ubuntu-latest
    needs: [ci]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: library
          path: "./dist/lib"
      - name: Publish to npm
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            npm publish ./dist/lib --provenance --access public --tag latest;
          else
            npm publish ./dist/lib --provenance --access public --tag ${{ github.ref_name }}-lts;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
