on:
  workflow_call:

jobs:
  cache_dependencies:
    uses: ./.github/workflows/cache_dependencies.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: cache_dependencies
    with:
      pnpm_store_path: ${{ needs.cache_dependencies.outputs.pnpm-store-path }}

  deploy_demo:
    name: Deploy Demo
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy_library:
    name: Deploy Library
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: library
          path: "./dist/lib"
      - name: Publish to npmjs.org
        run: |
          pnpm publish ./dist/lib --access public --tag v18-lts;
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
