on:
  - workflow_call

jobs:
  build_library:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Restore dependencies
        run: npm ci
      - name: Build for production
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: dist/lib
          retention-days: 5

  build_demo:
    name: Build Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Restore dependencies
        run: npm ci
      - name: Update application version
        run: sed -i "s/APP_VERSION = \".*\"/APP_VERSION = \"v$(jq -r .version package.json)-$(git rev-parse --short HEAD)\"/g" projects/demo/src/app/app.component.ts
      - name: Build for production
        run: npm run build:demo
      - name: Upload artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/demo/browser

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Restore dependencies
        run: npm ci
      - name: Run unit test
        run: npm run test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pgerke/ngx-mat-table-multi-sort
      - name: Extract version
        id: version-extraction
        run: echo "APP_VERSION=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.version-extraction.outputs.APP_VERSION }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Restore dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Restore dependencies
        run: npm ci
      - name: Run audit
        run: npm audit --omit=dev
